OBJ: a1.out a2.out a3.out a4.out
	
a1.out:
	gcc prog1.c -o prog1.out

a2.out:
	gcc prog2.c -o prog2.out

a3.out:
	gcc prog3.c -o prog3.out

a4.out:
	gcc prog4.c -o prog4.out

clean:
	rm prog1.out prog2.out prog3.out prog4.out
